// Alcohol % (or solvent notes) for making tinctures, keyed by lowercase herb name variants.
// Values are free-form strings to preserve notes like "fresh 60", "decoction with 20", etc.

const RAW: Record<string, string> = {
  alfalfa: 'vinegar',
  agrimony: '45 w/glyc',
  althea: '25%',
  angelica: '65%',
  ashwaganda: '40%',
  ashwagandha: '40%',
  avena: '',
  'artemesia/wormwood': '45%',
  artemesia: '45%',
  wormwood: '45%',
  astragalus: 'decoction/20%',
  anis: '60% (blended)',
  anise: '60% (blended)',
  artichoke: '50%',
  bacopa: '60%',
  baptisia: '65%',
  'bayberry root bark': '60%',
  bayberry: '60%',
  'birch leaf': '45%',
  'birch bark': '60%',
  'bee balm': '50%',
  'black haw': '50%',
  'black cohosh': '65%',
  'black pepper': '50%',
  'black walnut': '25%',
  'blessed thistle': '50%',
  'blue cohosh': '60%',
  'blue vervain': '50%',
  borage: '50%',
  boneset: '50%',
  burdock: '25% w/glyc',
  bugleweed: '50%',
  bupleurum: '40%',
  'california poppy': 'fresh 60%',
  catnip: '50%',
  "cat's claw": '50%',
  calamus: '60%',
  calendula: '60%',
  chamomile: '45%',
  chelidonium: 'fresh 60%',
  cinnamon: '60%',
  cleaver: '35%',
  cleavers: '35%',
  'comfrey root': 'cold infusion 25%',
  comfrey: 'cold infusion 25%',
  'couch grass': '45%',
  'cramp bark': '60%',
  damiana: '60%',
  'dandelion leaf': '40%',
  'dandelion root': '40%',
  dandelion: '40%',
  'devils club': '50%',
  "devil's club": '50%',
  "devil's claw": '25%',
  'devils claw': '25%',
  'dong quai': '65%',
  'echinacea augs': '45%',
  'echinacea augustifolia': '45%',
  'echinacea purpur leaf': '50%',
  'echinacea purpur root': '50%',
  'echinacea purpurea': '50%',
  echinacea: '45%',
  eclipta: '50%',
  eleuthero: '50%',
  erigeron: '50%',
  fennel: '60% (blended)',
  feverfew: '45%',
  gentian: '50%',
  'goldenrod/solidago': '50%',
  goldenrod: '50%',
  solidago: '50%',
  ginkgo: '50%',
  'gotu kola': '60%',
  goji: '25%',
  ginger: '75%',
  'gravel root': '50%',
  hawthorn: '50%',
  hops: '60%',
  'horse tail': 'tea only',
  horsetail: 'tea only',
  'horse chestnut': '50%',
  hypericum: '55% fresh / 60% dried',
  'st johns wort': '55% fresh / 60% dried',
  hyssop: '45–50%',
  inula: '25%',
  iris: '45%',
  juniper: '45%',
  'labrador tea': '',
  lavender: '55–60%',
  lavendar: '55–60%',
  "lady's mantle": '25%',
  'ladys mantle': '25%',
  'lemon balm': '50%',
  lemongrass: '50%',
  licorice: 'decoction/20%',
  linden: '25–40%',
  lomatium: '',
  lomatsium: '',
  lycopus: '50%',
  maca: '50%',
  meadowsweet: '50%/10% glyc',
  'milk thistle': '80–90%',
  marshmallow: '25%',
  mullein: '25%',
  'mullein root': '50%',
  mugwort: '25%',
  motherwort: '35–50%',
  'nettle leaf': '50%',
  nettle: '50%',
  'nettle root': '50%',
  oak: '50% w/glyc',
  ocimum: '65%',
  ociumum: '65%',
  'olive leaf': '50%',
  'olive leag': '50%',
  'orange peel': '60%',
  'oregon grape': '50%',
  oregano: '75%',
  osha: '',
  peppermint: '45%',
  parsley: '40%',
  'passion flower': '50%',
  passionflower: '50%',
  poppy: '50%',
  periwinkle: '55%',
  'peony white root': '50%',
  peony: '50%',
  plantain: '45%',
  'raspberry leaf': '25%',
  'red clover': '50%',
  rheum: '50%/10% glyc',
  rhodiola: '40%',
  rose: '50%',
  rosemary: '50%',
  rue: '55%/10V',
  rumex: 'decoction/20%',
  sage: '30%',
  sarsaparilla: '30%',
  sarsasparilla: '30%',
  'saw palmetto': '80%',
  'self heal': '50%/10% glyc',
  'self-heal': '50%/10% glyc',
  'scutellaria lateriflora': '50%',
  'scut lat fresh': '50%',
  schisandra: '50%',
  shatavari: '25–45%',
  shatavri: '25–45%',
  "shepherd's purse": '45%',
  'shepards purse': '45%',
  "solomon's seal": '',
  'solomens seal': '',
  spikenard: '50%',
  spilanthes: '55%/10V, 75%',
  'stone root': '45%',
  thyme: '45%',
  tulsi: '45%',
  valerian: '45%',
  vitex: '65% (blended)',
  yarrow: '40%',
  'wild lettuce': 'fresh 60–70%',
  'wild yam': '45%',
  'white oak': '25%',
};

// Normalize a herb display name for lookup
function normalize(name: string): string {
  return name.toLowerCase().replace(/\s+/g, ' ').trim();
}

export function getTinctureAlcohol(herbName: string): string | null {
  const key = normalize(herbName);
  if (key in RAW) return RAW[key] || null;

  // Partial match: check if any key starts with or is contained in the name
  for (const [k, v] of Object.entries(RAW)) {
    if (key.startsWith(k) || k.startsWith(key)) return v || null;
  }
  return null;
}
